# Generated by Django 3.1.5 on 2021-02-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
