# Generated by Django 3.1.5 on 2021-02-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtaapp', '0003_auto_20210201_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
